lint:
  actions_ci: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-vcftocounts_logo_light.png
    - docs/images/nf-core-vcftocounts_logo_light.png
    - docs/images/nf-core-vcftocounts_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-vcftocounts_logo_light.png
    - docs/images/nf-core-vcftocounts_logo_light.png
    - docs/images/nf-core-vcftocounts_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  included_configs: false
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.2.1
repository_type: pipeline

template:
  author: "Famke Bäuerle, Dorothy Ellis"
  description: Nextflow pipeline to convert (g)vcfs to matrices suitable for statistical
    analysis
  force: false
  is_nfcore: false
  name: vcftocounts
  org: qbic-pipelines
  outdir: .
  skip_features:
    - gitpod
    - codespaces
    - fastqc
    - adaptivecard
  version: 2.0.2dev
